import { useState } from "react";
import type { Lead } from "../types";
import { api, fmtDate } from "../api";

interface Props {
  lead: Lead;
  notify: (msg: string) => void;
  onMutated: (lead: Lead) => void;
}

export function SummarySection({ lead, notify, onMutated }: Props) {
  const [loading, setLoading] = useState(false);

  const generate = () => {
    setLoading(true);
    api
      .summarize(lead.id)
      .then(onMutated)
      .catch((e: Error) => notify(e.message))
      .finally(() => setLoading(false));
  };

  const s = lead.summary;

  return (
    <div className="section">
      <h3>
        AI lead summary
        <button className="btn btn-primary btn-sm" onClick={generate} disabled={loading}>
          {loading && <span className="spinner" />}
          {loading ? "Generating…" : s ? "Regenerate" : "Generate summary"}
        </button>
      </h3>
      {!s && !loading && (
        <div className="summary-card">
          <span style={{ color: "var(--ink-faint)" }}>
            No summary yet. Generate one to see who this lead is, what matters, what's happened, and what's
            missing.
          </span>
        </div>
      )}
      {s && (
        <div className="summary-card">
          <div className="summary-row">
            <div className="k">Who</div>
            <div className="v">{s.who}</div>
          </div>
          <div className="summary-row">
            <div className="k">What matters</div>
            <div className="v">{s.whatMatters}</div>
          </div>
          <div className="summary-row">
            <div className="k">What's happened</div>
            <div className="v">{s.whatHappened}</div>
          </div>
          {s.missingInfo && s.missingInfo.length > 0 && (
            <div className="summary-row">
              <div className="k">Missing / worth checking</div>
              <div className="missing-list">
                {s.missingInfo.map((m, i) => (
                  <span className="missing-chip" key={i}>
                    {m}
                  </span>
                ))}
              </div>
            </div>
          )}
          <div className={"source-tag" + (s.source === "fallback" ? " fallback" : "")}>
            {s.source === "fallback"
              ? "⚠ Local fallback summary (no model call). " + (s.fallbackNote || "")
              : "Generated by the model · " + fmtDate(s.generatedAt)}
          </div>
        </div>
      )}
    </div>
  );
}
