// Package ai generates the "Lead Summary" AI feature.
//
// Design decision: the summary is built from a strict, explicit context
// block (lead fields + notes + open tasks) rather than letting the model
// see the whole JSON blob, so we know exactly what reaches the model and can
// say so in the demo. If the model call fails, times out, or returns
// something too thin to be useful, we fall back to a deterministic,
// rule-based summary built from the same local data - so the feature never
// just breaks in front of a user. The fallback is clearly labeled as such.
package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"crm/internal/store"
)

const (
	defaultModel   = "gpt-4o-mini"
	requestTimeout = 15 * time.Second
)

type Client struct {
	apiKey string
	model  string
	http   *http.Client
}

// NewClient reads config from environment variables:
//
//	OPENAI_API_KEY - required for real model calls; if unset, every
//	                  summary is generated by the local fallback.
//	OPENAI_MODEL   - optional override of the model ID.
func NewClient() *Client {
	model := os.Getenv("OPENAI_MODEL")
	if model == "" {
		model = defaultModel
	}
	return &Client{
		apiKey: os.Getenv("OPENAI_API_KEY"),
		model:  model,
		http:   &http.Client{Timeout: requestTimeout},
	}
}

// modelResponse is the strict JSON shape we ask the model to return.
type modelResponse struct {
	Who          string   `json:"who"`
	WhatMatters  string   `json:"whatMatters"`
	WhatHappened string   `json:"whatHappened"`
	MissingInfo  []string `json:"missingInfo"`
}

// Summarize produces a lead summary, calling the model if configured and
// falling back to a local, rule-based summary otherwise or on any failure.
func (c *Client) Summarize(ctx context.Context, lead *store.Lead) *store.Summary {
	if c.apiKey == "" {
		return c.fallback(lead, "OPENAI_API_KEY is not set, so no model call was made.")
	}

	resp, err := c.callModel(ctx, lead)
	if err != nil {
		return c.fallback(lead, fmt.Sprintf("Model call failed (%v).", err))
	}
	if isWeak(resp) {
		return c.fallback(lead, "Model response was too thin to be useful (missing or empty fields).")
	}

	return &store.Summary{
		Who:          resp.Who,
		WhatMatters:  resp.WhatMatters,
		WhatHappened: resp.WhatHappened,
		MissingInfo:  resp.MissingInfo,
		GeneratedAt:  time.Now(),
		Source:       "model",
	}
}

func isWeak(r *modelResponse) bool {
	return len(strings.TrimSpace(r.Who)) < 3 ||
		len(strings.TrimSpace(r.WhatMatters)) < 3 ||
		len(strings.TrimSpace(r.WhatHappened)) < 3
}

// buildContext assembles exactly what we send the model - deliberately
// explicit so it's easy to describe in a demo ("this is all that reaches the
// model: these fields, these notes, these open tasks").
func buildContext(lead *store.Lead) string {
	var b strings.Builder
	fmt.Fprintf(&b, "Lead: %s\n", lead.Name)
	if lead.Title != "" {
		fmt.Fprintf(&b, "Title: %s\n", lead.Title)
	}
	fmt.Fprintf(&b, "Company: %s\n", lead.Company)
	if lead.Email != "" {
		fmt.Fprintf(&b, "Email: %s\n", lead.Email)
	}
	if lead.Phone != "" {
		fmt.Fprintf(&b, "Phone: %s\n", lead.Phone)
	}
	if lead.Source != "" {
		fmt.Fprintf(&b, "Source: %s\n", lead.Source)
	}
	if lead.DealValue > 0 {
		fmt.Fprintf(&b, "Deal value: %d\n", lead.DealValue)
	}
	fmt.Fprintf(&b, "Pipeline stage: %s\n", lead.Stage)

	if len(lead.Notes) == 0 {
		b.WriteString("Notes/activities: none logged yet.\n")
	} else {
		b.WriteString("Notes/activities (newest first):\n")
		for _, n := range lead.Notes {
			fmt.Fprintf(&b, "- [%s] %s: %s\n", n.CreatedAt.Format("2006-01-02"), n.Kind, n.Content)
		}
	}

	open := 0
	for _, t := range lead.Tasks {
		if !t.Done {
			open++
			fmt.Fprintf(&b, "Open task: %s\n", t.Title)
		}
	}
	if open == 0 {
		b.WriteString("Open tasks: none.\n")
	}
	return b.String()
}

func (c *Client) callModel(ctx context.Context, lead *store.Lead) (*modelResponse, error) {
	system := "You are a sales assistant summarizing a CRM lead for a busy sales rep. " +
		"Respond with ONLY a JSON object (no prose, no markdown fences) with exactly these keys: " +
		`"who" (1 sentence: who this person/company is), ` +
		`"whatMatters" (1-2 sentences: what's important about them - deal size, urgency, role, concerns), ` +
		`"whatHappened" (1-2 sentences: what has happened so far in plain language), ` +
		`"missingInfo" (a JSON array of short strings naming fields or context that are missing or would help, e.g. "phone number", "no notes logged yet"; empty array if nothing important is missing). ` +
		"Base your answer only on the context given. Do not invent facts."

	body := map[string]any{
		"model":           c.model,
		"max_tokens":      500,
		"response_format": map[string]string{"type": "json_object"},
		"messages": []map[string]string{
			{"role": "system", "content": system},
			{"role": "user", "content": buildContext(lead)},
		},
	}
	raw, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost,
		"https://api.openai.com/v1/chat/completions", bytes.NewReader(raw))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+c.apiKey)

	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var apiResp struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
		Error *struct {
			Message string `json:"message"`
		} `json:"error"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, fmt.Errorf("decoding API response: %w", err)
	}
	if resp.StatusCode != http.StatusOK {
		if apiResp.Error != nil {
			return nil, fmt.Errorf("API error %d: %s", resp.StatusCode, apiResp.Error.Message)
		}
		return nil, fmt.Errorf("API error %d", resp.StatusCode)
	}
	if len(apiResp.Choices) == 0 {
		return nil, fmt.Errorf("API returned no choices")
	}

	text := strings.TrimSpace(apiResp.Choices[0].Message.Content)
	text = strings.TrimPrefix(text, "```json")
	text = strings.TrimPrefix(text, "```")
	text = strings.TrimSuffix(text, "```")

	var parsed modelResponse
	if err := json.Unmarshal([]byte(strings.TrimSpace(text)), &parsed); err != nil {
		return nil, fmt.Errorf("model did not return valid JSON: %w", err)
	}
	return &parsed, nil
}

// fallback builds a summary entirely from local data - no network call.
// It's what keeps the AI feature demo-able even with no API key or a flaky
// connection.
func (c *Client) fallback(lead *store.Lead, reason string) *store.Summary {
	who := lead.Name
	if lead.Title != "" {
		who = fmt.Sprintf("%s, %s at %s", lead.Name, lead.Title, lead.Company)
	} else {
		who = fmt.Sprintf("%s at %s", lead.Name, lead.Company)
	}

	var matters []string
	if lead.DealValue > 0 {
		matters = append(matters, fmt.Sprintf("potential deal value of %d", lead.DealValue))
	}
	matters = append(matters, fmt.Sprintf("currently in the %q pipeline stage", string(lead.Stage)))
	if lead.Source != "" {
		matters = append(matters, fmt.Sprintf("came in via %s", lead.Source))
	}
	whatMatters := strings.Join(matters, "; ")

	var whatHappened string
	if len(lead.Notes) == 0 {
		whatHappened = "No notes or activities have been logged yet for this lead."
	} else {
		latest := lead.Notes[0]
		whatHappened = fmt.Sprintf("%d activities logged; most recent (%s, %s): %s",
			len(lead.Notes), latest.CreatedAt.Format("Jan 2"), latest.Kind, truncate(latest.Content, 160))
	}

	var missing []string
	if lead.Phone == "" {
		missing = append(missing, "phone number")
	}
	if lead.Title == "" {
		missing = append(missing, "job title")
	}
	if lead.Email == "" {
		missing = append(missing, "email address")
	}
	if lead.DealValue == 0 {
		missing = append(missing, "estimated deal value")
	}
	if len(lead.Notes) == 0 {
		missing = append(missing, "no notes/activities logged yet")
	}
	openTasks := 0
	for _, t := range lead.Tasks {
		if !t.Done {
			openTasks++
		}
	}
	if openTasks == 0 {
		missing = append(missing, "no open follow-up task")
	}

	return &store.Summary{
		Who:          who,
		WhatMatters:  whatMatters,
		WhatHappened: whatHappened,
		MissingInfo:  missing,
		GeneratedAt:  time.Now(),
		Source:       "fallback",
		FallbackNote: reason,
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "..."
}
